ALTER TABLE COMMENT ALTER COLUMN COMMENTATOR BIGINT NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN VIEW_COUNT BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN COMMENT_COUNT BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN LIKE_COUNT BIGINT DEFAULT 0 NOT NULL;
